name: try run test

on:

  pull_request:
    branches:
      - main


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: setUp JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: gran execute permission for gradlew
        run: chmod +x gradlew

      - name: run check function
        run: |
          kotlin -e "$(curl -s https://github.com/ahmedfikry24/Jetpack-Compose-Tips/blob/ci-cd/app/src/main/java/com/example/jetpackcomposetips/RegularTest.kt | grep -A 10 'fun check()')"